version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/bindings/go"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
  
  - package-ecosystem: "gomod"
    directory: "/tools/osv-linter"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/tools/ghsa"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/tools/redhat"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
